### PR TITLE
ci: Remove Release assets

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Issue Description

Removes release assets from [release](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/2.7.0)

Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1740

### Approach

* Remove assets from CI
* Update README instructions

### TODOs before merging

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by dplewis** [comment]
@mtrezza this is ready for review

**Comment by mtrezza** [comment]
I seem to remember that we recently did not have assets in releases and there was someone requesting they'd be added. I'm not sure about the use cases for these assets - are there any other than adding the SDK as a file directory to a project?

**Comment by dplewis** [comment]
> I seem to remember that we recently did not have assets in releases

Assets have been available since the beginning of the SDK.

> Any good reason someone would need to add the SDK as a file directly

I'm also not sure about the use cases for these assets unless they can't get SPM to work.

**Comment by mtrezza** [comment]
> Assets have been available since the beginning of the SDK.

They haven't been available at some point, I believe with the introduction with SPM. We even have added a manual CI workflow to add the assets in case the process fails. I remember there was a complaint, but I can't find it.

**Comment by mtrezza** [comment]
Let's leave this open for some days and the go ahead and remove them, I'd suggest.

**Comment by dplewis** [comment]
@mtrezza A use case is if you need to develop using an offline framework.

**Comment by mtrezza** [comment]
I'm continuing the discussion in https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1740#issuecomment-1747122373, because it's not PR related.

**Comment by mtrezza** [comment]
@dplewis I notice that this PR made some more changes to the README that are missing in https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1744. Is this PR still useful?

**Comment by dplewis** [comment]
I’ll create another PR as there maybe merge conflicts. This PR is useful because it removes publishing the assets to GitHub on version release

**Comment by mtrezza** [comment]
Other PR: https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1745

**Pull request closed without merging**
