### PR TITLE
ci: API reference documentation not generated

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Issue Description

Parse.h header file was moved in https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1683 preventing the api documentation from generating. 

```
error: error reading '/Users/runner/work/Parse-SDK-iOS-OSX/Parse-SDK-iOS-OSX/Parse/Parse/Parse.h'
```

Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1702

### Approach
* Allow jazzy script to fail with non-zero exit code
* Correct the proper header path

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Thanks a lot for this!

**Comment by dplewis** [comment]
This is ready to merge

**Comment by dplewis** [comment]
They won’t be published until the next release

**Comment by dplewis** [comment]
The manual docs workflow itself has errors and can't generate the docs. Look at the CI closely. It looks like it passes its actually failing.

Screen Shot 2023-03-07 at 12 06 02 PM

**Comment by mtrezza** [comment]
Should we try to get the manual workflow working, so we know that with the next release it will work automatically?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.2.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/2.2.0)

**Pull request merged**
