### PR TITLE
1.17.3 release tweaks

### PR DESCRIPTION
**Pull request by drdaz**
Just some final tweaks before we release

### CODE REVIEW

**Comment by TomWFox** [comment]
@drdaz could you wait for review in future?

**Comment by drdaz** [comment]
@TomWFox Sure! My bad.

**Comment by TomWFox** [comment]
@drdaz Would you like to tag the release?

**Comment by drdaz** [comment]
Sure 🙂

These changes are ok I take it?

**Comment by TomWFox** [comment]
Looks good, although we don't usually reference issues in the changelog - `([#1411](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1411))`

**Comment by drdaz** [comment]
@TomWFox Ahh... I thought you wrote that bit? It came at some point during the FB libs PR. 😃

lol I'll fix it.

**Comment by TomWFox** [comment]
Ah, I think you're right!

**Comment by drdaz** [comment]
I'm unable to push tags? 
I'm creating it against master here and pushing.

**Comment by TomWFox** [comment]
You can just do it in the GitHub ui

**Comment by drdaz** [comment]
Then I'll need to make the release, right? Should I build a release locally and attach the binaries? Or how does this go?

**Comment by TomWFox** [comment]
For other repos we just create the release in the github ui, I'm not sure about the binaries, does the ci attach them maybe?

**Comment by drdaz** [comment]
No idea 😃

I mean... I can give it a try. If something's missing, we can add it.

**Comment by TomWFox** [comment]
Go for it!

**Comment by drdaz** [comment]
Ka-ching.

Do you need to update Cocoapods?

**Comment by TomWFox** [comment]
should do that through ci

**Comment by TomWFox** [comment]
Or not, the CocoaPods build failed

**Comment by drdaz** [comment]
Indeed. It's broken :(

**Comment by drdaz** [comment]
I mean the Cocoapods build is broken. Pretty sure using Cocoapods works fine.

**Pull request merged**
