### PR TITLE
Fix PFCommandCache memory leak

### PR DESCRIPTION
**Pull request by antoinelamy**
screen shot 2017-06-05 at 8 13 00 am

### CODE REVIEW

**Comment by flovilmart** [comment]
Nice Thanks!

**Comment by antoinelamy** [comment]
The builds seems stuck on Travis, is this a known issue? I doubt that this commit is causing this.

**Comment by flovilmart** [comment]
Did you try running the script that is run on CI locally?

**Comment by antoinelamy** [comment]
It took me a while to recreate the travis environment but I managed to get the script working and it is confirmed that my modification cause a regression. It's a bit odd but it seems that the `PFEventuallyQueue` is responsible for retaining itself by design. It will take more time to investigate so I'm closing this PR for the moment.

**Comment by flovilmart** [comment]
Also, a cycle is not necessarily a leak. Are those objects leaked when deallocated?

**Comment by antoinelamy** [comment]
@flovilmart in my case it was a leak

**Pull request closed without merging**
