### PR TITLE
update FBSDK from 6.x to 8.x

### LINKED ISSUE #1578: FBSDKCoreKit dependency issue
Hello,

With Parse/FacebookUtils 1.19.1 use FBSDKCoreKit/Basics 6.5.2

Therefore, it's not possible to use latest version of FBAudienceNetwork (https://github.com/CocoaPods/Specs/blob/master/Specs/2/1/5/FBAudienceNetwork/6.2.0/FBAudienceNetwork.podspec.json)

"dependencies": {
    "FBSDKCoreKit/Basics": [
      ">= 7.0.1"
    ]

can you upgrade to FBSDKCoreKit to ">= 7.0.1"

by the way, same issue for other FB kits

### PR DESCRIPTION
**Pull request by eeallen1**
Facebook can't use the Advanced Matching feature for app events on iOS 14 devices with any FBSDk version older than 8.0. As far as I can tell, there are no breaking changes to ParseFacebookUtils

Close #1578

### CODE REVIEW

**Comment by cbaker6** [comment]
Waiting to get the CI up and running in #1581 so we can make sure the update passes all of the tests

**Comment by cbaker6** [comment]
Can you rebase with the master branch?

**Comment by drdaz** [comment]
🤔

**Comment by drdaz** [comment]
It looks like the current version of FBSDK requires a minimum deployment target of 9.0 in the podspec, which is what's causing Cocoapods to fail.

**Comment by cbaker6** [comment]
> EDIT: It looks like current Xcode feels the same way, since it's spitting up those warnings about supported OS versions.

right, Xcode 12 wants this on all projects. I didn’t update the project in the actions PR just in case it broke something.

**Comment by drdaz** [comment]
Imma try updating it here.

**Comment by drdaz** [comment]
@cbaker This could probably use a review from somebody not me

**Comment by cbaker** [comment]
> @cbaker This could probably use a review from somebody not me. But it's ready I think.

yezzir

**Comment by drdaz** [comment]
Sorry @cbaker, I meant @cbaker6 😂

**Comment by cbaker** [comment]
> Sorry @cbaker, I meant @cbaker6 😂

I know happens a couple of times every other week 🤣 GL guys,

**Review by cbaker6 — APPROVED** [review]
LGTM!

**Comment by sarojkumarojha** [comment]
Hi @cbaker6 is this FBSDK from 6.x to 8.x is done ? when can we expect a release ? will it be part of 1.19.2 ?

**Comment by drdaz** [comment]
It's merged into main. You should be fine using the current commit until there's a release.

**Comment by sarojkumarojha** [comment]
@drdaz 
Is there any release from Parse near future with FBSDK > 9.x ?

**Comment by drdaz** [comment]
I've been tied up with work for most of the beginning of this year. I should have some time to work here in the next couple weeks. I'll try and get one pushed then.

**Comment by JulienLevallois** [comment]
> It's merged into main. You should be fine using the current commit until there's a release.

Hi @drdaz I installed the last release 1.19.1 with CoCoapods + Parse/FacebookUtils and it seems to install Facebook version 6.5.2, how can I upgrade to version 8 minimum?

Thanks

@sarojkumarojha have you been successful?

Capture d’écran 2021-03-10 à 10 51 17

**Comment by drdaz** [comment]
@JulienLevallois I'm working on a release PR now. If you need it before the release is final, point your Cocoapods reference at the current commit on the main branch.

**Comment by JulienLevallois** [comment]
@drdaz  Thanks a lot

**Pull request merged**
