### PR TITLE
Release 1.19.2

### LINKED ISSUE #1608: Trying to Install Parse/FacebookUtils with CocoaPods
Hi,

Im trying to install Parsse/FacebookUtils with cocoaPods and I got this error. I want to install it for Facebook 9.0

Capture d’écran 2021-03-05 à 20 23 33

I got theses errors

Capture d’écran 2021-03-05 à 20 23 38

If someone have one idea, thanks

### PR DESCRIPTION
**Pull request by drdaz**
By popular demand, updates the Facebook SDK to 9.x.

Close #1608

### CODE REVIEW

**Comment by drdaz** [comment]
@cbaker6 @TomWFox I don't have access to the Settings tab, so I can't access Secrets. Which is, I think, where the Cocoapods trunk token goes with this sweet new Actions getup.

Do we still need to worry about that? 🤔

**Comment by TomWFox** [comment]
Its actually sharing an org level secret with a token that is shared with the Swift SDK & iOS Live query so with the high frequency of releases with any luck the token won't expire 🤞

**Review by TomWFox — APPROVED** [review]
LGTM 👍

**Review by cbaker6 — APPROVED** [review]
LGTM! 

Update: @drdaz I added the issue to the description so it automatically closes when you merge

**Comment by drdaz** [comment]
@cbaker the release worked you legend. There are downloads again 🎉🥳

**Comment by drdaz** [comment]
Cocoapods deployed too!!!1!

**Comment by TomWFox** [comment]
Awesome, thanks @drdaz & @cbaker6 🥳

**Pull request merged**
