### PR TITLE
Makes FacebookUtils tvOS a subspec so iOS apps can move forward

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by tahoecoop** [comment]
Any status on this PR merge? Thanks @flovilmart !

**Comment by flovilmart** [comment]
Sorry I completely forgot about that! If that's the direction everyone is ready to go, I'm happy with it !

**Comment by flovilmart** [comment]
I'll have a deeper look as well as it seems all dependencies have been properly bumped on facebook side.

**Comment by tahoecoop** [comment]
Sounds great, I really appreciate all your assistance!

**Pull request merged**
