### PR TITLE
feat: Remove `ParseFacebookUtils` and `ParseTwitterUtils`

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Issue Description

Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1780
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1775
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1764
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1773

### Approach

Remove ParseFacebookUtils and ParseTwitterUtils

### CODE REVIEW

**Comment by mtrezza** [comment]
@parse-community/ios-sdk, @chriscborg, @matteolongeri-ovolab, @SOGAPPS, @gmohiuddin215, @JustinGanzer, @nmoersch-calimoto, @caliandi is everyone fine with this?

**Comment by mtrezza** [comment]
Change log entry:

> BREAKING CHANGE: Removes convenience utilities `ParseFacebookUtils` and `ParseTwitterUtils`, instead add the 3rd party authentication SDK to log in and provide the authentication data to `PFUser.logInWithAuthType` to link the Parse User.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.0.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/3.0.0)

**Comment by mathieulb** [comment]
@mtrezza , is there any official documentation on how to « add the 3rd party authentication SDK to log in and provide the authentication data to PFUser.logInWithAuthType to link the Parse User » ? According to the front page, the documentation is supposed to be at https://docs.parseplatform.org/ios/guide/ , but in there, the sample code still refers to PFFacebookUtils, which causes `Cannot find 'PFFacebookUtils' in scope` with ParseObjC >= 3.0.

Likewise for PFTwitterUtils.

**Comment by mathieulb** [comment]
@mtrezza , In the meantime, I added to my project all `*.h` and `*.m` from all `Source` and `Internal` folders of `ParseFacebookUtils`, `ParseFacebookUtilsiOS` and `ParseTwitterUtils`, added a `Bridging-Header.h`, fixed a few `#import` lines & added back `NSInteger const kPFErrorFacebookInvalidSession = 251;`. That fixed what this pull-request broke. It required installing Facebook SDK < 17, because 17 breaks compatibility.

**Pull request merged**
