### PR TITLE
ci: Optimize CI workflow performance

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Issue Description

The current ci workflow doesn't allow for an easy way to debug failing tests. The PR saves ~10 minutes of CI time, allows for easier debugging of flaky tests and fixes some flaky tests

Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1634

### Approach

* Refactor all test jobs into a matrix
* Run tests against iPhone 14 simulator
* Run tests against Xcode 14
* Ensure Ruby Gem Cache works
* Add Carthage Cache
* Upload test logs to artifacts to debug failing tests
* Use XCODEBUILD instead of XCPRETTY to show more test details and derivedData folder location
* Pin MacOS version instead of `latest`
* Disabled extremely flaky tests

### CODE REVIEW

**Comment by dplewis** [comment]
@mtrezza This should also fix the manual documenation release as well

**Comment by mtrezza** [comment]
That's really cool

**Comment by dplewis** [comment]
@mtrezza The CI does pass. I think the old CI is trying to run.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.2.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/2.2.0)

**Comment by dplewis** [comment]
@mtrezza Can you run the manual docs generation workflow?

**Comment by mtrezza** [comment]
I did and it got published

**Pull request merged**
