### PR TITLE
ci: Fix failing macOS tests

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Issue Description

Looks like this was manually added to the scheme instead of going through XCode UI. Hopefully this will reduce the amount of flaky tests.

Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1677

### CODE REVIEW

**Comment by dplewis** [comment]
@mtrezza Codecov is broken

```
{'detail': ErrorDetail(string='Missing "owner" argument. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```

**Comment by dplewis** [comment]
@mtrezza Looks like tests are passing consistently. Can we merge this?

**Comment by mtrezza** [comment]
Sure, thanks for the fix!

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.2.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/2.2.0)

**Pull request merged**
