### PR TITLE
Updating build files for building with Xcode11

### PR DESCRIPTION
**Pull request by noobs2ninjas**
This is preparation for issue #1446 aka iOS 13 update.
 
- Updated gem versions
- Updated circle config
- Updated Ruby Version.
- Rebuilt Gemfile.lock
- Updated Xcode version used.

### CODE REVIEW

**Comment by drdaz** [comment]
Looking at the failures you're getting for the iOS tests, those were already failing intermittently. And as something new here, they're being reported as crashed tests rather than failures (which is a nice improvement).

So those failures probably don't have anything to do with your changes 🙂

**Comment by noobs2ninjas** [comment]
@drdaz I also updated the LiveQuery build files. I'd be curious if they are experiencing similar errors. 

Unfortunately, I think the main issue is that we updated to xcode11 which brings with it different warning/error levels and I think even its own deprecations because it uses different API versions for iOS 13.

 I'll try to take a look at it later on. I literally spent the last 3 hours thinking trying to figure out why LiveQuery wouldnt complete the docs build just to find out that Jazzy 0.11.0 is broken!  If youd like to take a stab at either these errors or [ParseLiveQuery's](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/pull/210) failing mac build I'd love some help. 👍

**Comment by noobs2ninjas** [comment]
I'm curious if I dropped the Xcode version down to 10.2 but left the update gems etc if that would fix and allow you to push 1.17.3 @drdaz. After I catch some sleep I'll get it a shot. This way we can get your release out without doing iOS 13 updates.

**Comment by drdaz** [comment]
@noobs2ninjas Great work! 

Yeah it would be nice if the infrastructure updates play nice with a current release of Xcode. I would sort of expect them too... but we'll see. Looking forward to hear how that goes!

> I'll try to take a look at it later on. I literally spent the last 3 hours thinking trying to figure out why LiveQuery wouldnt complete the docs build just to find out that Jazzy 0.11.0 is broken! If youd like to take a stab at either these errors or ParseLiveQuery's failing mac build I'd love some help. 👍

I'll try and find some time during the week to look at it, assuming you haven't ploughed through it by then 😃

**Comment by noobs2ninjas** [comment]
Jazzy pushed an update to fix. So, I'm doing one final update for that. That that it fixes the failed tests.

**Comment by noobs2ninjas** [comment]
@drdaz did you want to go ahead and merge this so you can get your last release out?

**Comment by drdaz** [comment]
@noobs2ninjas You said you'd try reverting to Xcode 10.x and see if everything kept ticking? I feel a little weird moving master to an unreleased Xcode.

**Comment by drdaz** [comment]
Ahh. It's been merged 😃

**Comment by noobs2ninjas** [comment]
I was thinking about it and while it does feel weird we have to remember that these settings have nothing to do with developers local machines or how they develop using the framework. They are only for Travis and CircleCI which according to them Xcode11 is open for use.

**Comment by noobs2ninjas** [comment]
Haha also yea...I forgot to ask about it before merging it. However, if you disagree I am totally willing to move it to 10.2 just for the purpose merging with master so 1.17.3 can deploy.

**Comment by drdaz** [comment]
They're open for use on the service, but the software is still pre-release. 

I thought it was a useful feature for CI when actually developing using the pre-release software. I'm not sure what else it could be used for?

I do think we should drop the version for the 1.17.3 release. I honestly think I'd rest easier. 😃

**Comment by noobs2ninjas** [comment]
Haha wow. Apparently Xcode 11 is released. This must have literally just happened because while I dont see it reflected on the mac app store yet according to [this]([this](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes) ) official Apple document Xcode 11 is out. I went to check because I had a hunch since I was watching the iPhone 11 reviews that are coming out. Which BTW the current Xcode Version is 10.3 on the store? When was there a 10.3?

**Comment by drdaz** [comment]
According to [this](https://developer.apple.com/download/release/) official website the latest release is 10.3 😂

And yeah I've been on 10.3 for a while. Isn't that what you're running?

**Comment by noobs2ninjas** [comment]
Haha I am. I guess all I've been seeing on Travis and Circle is 10.2 so I just assumed that was the latest. When you install the Xcode 11 beta it sets itself as the default so I guess I just never payed attention to what version 10 is on. 

Well I guess lets just give it a day or two and see what happens because that document says pain as day "Xcode 11 is available in the Mac App Store and includes SDKs for iOS 13". I'm thinking they must have released the document before their deployment servers had built and pushed the new version out.

**Comment by noobs2ninjas** [comment]
Wow! Yea that must be the case. Everything but iPad OS releases in 2 days! iOS, watchOS, macOS, tvOS.

**Comment by drdaz** [comment]
macOS doesn't release in 2 days; 'some time in October' is the current timeframe. Likewise there isn't an official release date for Xcode 11 - it's on GM Seed 2, so it *should* be soon, but there's no guarantee on when, nor if it will actually be the current build.

As an aside, I don't have a clue what's happened during the night (it's morning where I am now). I've got so many email threads stuffed with commits and comments about these repos that it's kinda hard to know where we are here.

**Pull request merged**
