### PR TITLE
fix: Compilation errors in `ParseLiveQuery` using `Starscream` 4.0.6

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Issue Description

There are many reasons why these issues could occur.

`Type 'Client' does not conform to protocol`
`Switch must be exhaustive`

Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1738

### Approach

You can replicate this issue by adding ParseLiveQuery to the tvOS starter project via SPM.

* Bump starscream to 4.0.6
* Remove starscream from Carthage
* Remove bolts-swift from Carthage
* Add starscream changes from update
* Add local SDK from SPM to tvOS starter
* Deploy for iOS 12

### CODE REVIEW

**Comment by dplewis** [comment]
When adding Starscream to the `ParseLiveQuery` project as a swift package dependency I got this. I'm using my own fork for now. We may need to fork this on ParsePlatform.

Screenshot 2023-10-05 at 6 00 25 PM

**Comment by mtrezza** [comment]
How is that possible for a public repository?

**Comment by dplewis** [comment]
I figured it out

**Comment by dplewis** [comment]
@mtrezza This is ready to merge.

**Review by mtrezza — APPROVED** [review]
Looks good - an impressive tour de force!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.7.3](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/2.7.3)

**Pull request merged**
