### PR TITLE
Updates xctoolchain to fix build

### PR DESCRIPTION
**Pull request by drdaz**
Apple TV build has been failing. Hopefully this helps.

### CODE REVIEW

**Comment by drdaz** [comment]
Hmm this PR contains a change that's already been merged...

**Comment by flovilmart** [comment]
@drdaz this helps definitely! Thanks for the PR!

**Comment by flovilmart** [comment]
The facebook tests are failing are it requires to build against Xcode 10.

**Comment by drdaz** [comment]
Really? Looking at the change, I've used the wrong syntax :D

**Comment by drdaz** [comment]
Yeah the build fails on my change :(

**Pull request merged**
