### PR TITLE
Add Xcode 8.0 Swift 3.0 support

### PR DESCRIPTION
**Pull request by katopz**
fixed https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/1033

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by a4arpan** [comment]
Any progress on this pull request yet?

**Comment by flovilmart** [comment]
@katopz , thanks for the PR, can you update the .travis.yml in order to use xcode8 instead of 7.3 ? https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-8

**Comment by katopz** [comment]
@flovilmart I'm just add Xcode 8.2.1 (8C1002), iOS 8,9,10 support please check.

**Comment by flovilmart** [comment]
In the Cartfile.resolved it says bolts should be a 1.8.4, can you double check that all version matches (submodules, Cartfile, .podspec)

**Comment by katopz** [comment]
@flovilmart
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/pull/1045/commits/030b879790f531df93171ca1fdec84a72339f221 should be `1.8.4` as expected but it will show some warning.
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/pull/1045/commits/05900399d2fe535bf96298247a1f62649303df29 point to master to resolve that warning.

I'm not sure that you want me to revert last commit to https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/pull/1045/commits/030b879790f531df93171ca1fdec84a72339f221 for `1.8.4`?

**Comment by flovilmart** [comment]
I just wanna make sure we don<t have different versions of dependencies for each releases.

**Comment by katopz** [comment]
@flovilmart Consider it done :)

**Comment by nyxee** [comment]
can you please provide some tested code samples that work with XCode 8.2 and Swift 3 and OSX and iOS please

**Comment by flovilmart** [comment]
I started from your branch and merged and also updated all other projects in order to work A1 with swift4. One thing to know, relations don't work correctly (with `@NSManaged`)

**Pull request closed without merging**
