### PR TITLE
Updating submodule versions to fix build. 

### PR DESCRIPTION
**Pull request by noobs2ninjas**
I might need to still update the xcodebuild tools again and update the submodule version again to fix apple tv simulator error.

### CODE REVIEW

**Comment by noobs2ninjas** [comment]
This is awaiting a xctoolchain update so I can do a submodule update and push the changes here. After that we should be good to go.

**Comment by drdaz** [comment]
Aww yeah. https://travis-ci.org/parse-community/Parse-SDK-iOS-OSX/builds/589620853 👌🏼

**Comment by noobs2ninjas** [comment]
Haha did you check the log? It's like 11,700 lines long on the deployment job.

**Comment by drdaz** [comment]
I hadn't. I'm a simple man. I see green and I'm happy.

But now I have and yeah that's a big log ^^

**Comment by drdaz** [comment]
Dude. The whole suite passed. 👏🏼

**Comment by noobs2ninjas** [comment]
Haha been a little while since that happened?

**Comment by drdaz** [comment]
I mean, it'll be interesting to see how consistent it is. The (x)OS tests have been inconsistent for a long time. I have some hope these updates might help with that.

**Comment by noobs2ninjas** [comment]
Im curious why the iOS tests all the sudden pass. Doesnt make sense to me.

**Comment by drdaz** [comment]
It's not all of a sudden. They pass most of the time.

**Comment by drdaz** [comment]
Or... at least some of the time. That's what I mean; they're inconsistent.

**Comment by noobs2ninjas** [comment]
Spoke too fast. Master CircleCI build still fails.

**Comment by drdaz** [comment]
Yeah; still inconsistent. 😞

The same tests are inconsistent locally too which is kind of comforting.

**Pull request merged**
