### PR TITLE
Specified Bolts "Tasks" in subspecs dependencies for facebook utils. …

### PR DESCRIPTION
**Pull request by tealshift**
…This removes Bolts/AppLinks and thus UIWebView.

### CODE REVIEW

**Comment by tealshift** [comment]
I forgot to note that this addresses issue: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1443

**Comment by drdaz** [comment]
Yeah I like it. Let's merge it.

**Comment by drdaz** [comment]
This actually brings it in line with the rest of the podspec. 👍🏼

**Comment by mmimeault** [comment]
Hello, could it be possible to make a new release with that change. We are trying to remove all usages of UIWebView in our project. Thanks in advance.

**Comment by benpackard** [comment]
Just to note that apps using UIWebView will not be accepted from April. https://developer.apple.com/news/?id=12232019b

**Comment by chriscborg** [comment]
Has a release been created for this fix? Or do you think it's safe to use master directly as it is. I'm still getting references to UIWebview in version 1.17.3 and unfortunately no new apps are being approved because of this.

**Comment by TomWFox** [comment]
No release yet, we’re working on it.

I think it’s safe to use master at the moment but @drdaz @noobs2ninjas are in a better position to answer that.

**Comment by drdaz** [comment]
Yeah master should be fine. Pls do let us know if it isn't :)

**Pull request merged**
