### PR TITLE
feat: Add `PFObject.isDataAvailableForKey` to check if data is available for individual key

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Issue Description

This PR avoid crashing when we try to get data from key which is not fetched. You can check if data is available for a PFObject but not by individual key.

Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1595

### Approach

```
if user.isDataAvailable(forKey: "username") {
 // ok
}
```
or
```
if let username = user["username"] {
// username is available
}
else {
// username is unavailable, please fetch it
}
```

### TODOs before merging

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by mtrezza** [comment]
This is in case a key exists in the DB, but the key value is not fetched on the SDK side?

**Comment by dplewis** [comment]
> This is in case a key value may exist in the DB, but the key value is not fetched on the SDK side, so the SDK doesn't know the current key value?

This is correct. I've updated the PR.

**Comment by dplewis** [comment]
@mtrezza This is ready for review

**Comment by mtrezza** [comment]
Test fails, flaky?

**Comment by dplewis** [comment]
@mtrezza the CI is broken. Looks like an issue with Ruby and Bundler versioning. Can you fix it?

**Comment by mtrezza** [comment]
See https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1777

**Comment by mtrezza** [comment]
It doesn't have a test, do you want to add one, or shall I merge without it?

**Comment by dplewis** [comment]
The test exist when this was private. No additional test needed

**Comment by mtrezza** [comment]
> The test exist when this was private.

What does that mean?

**Comment by dplewis** [comment]
Sorry, I mean the test are there already. No need to write new ones

**Comment by mtrezza** [comment]
If the test is there already, why doesn't it fail without this PR?

**Comment by mtrezza** [comment]
Is this a bug fix? From the description is seems so...

> This PR avoid crashing when we try to get data from key which is not fetched.

**Comment by dplewis** [comment]
This is a feature

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.0.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/3.0.0)

**Pull request merged**
