### PR TITLE
Fixes macOS tests

### PR DESCRIPTION
**Pull request by drdaz**

### CODE REVIEW

**Comment by drdaz** [comment]
@TomWFox Sorry I got a bit excited. This should fix the macOS tests.

**Comment by TomWFox** [comment]
No worries, for anyone following along there is discussion for this in #1427

**Comment by drdaz** [comment]
Well... I may have jumped the gun on the 'fix'. But it builds.

The macOS tests pass locally for me. Looks like I may have broken something though. I'll look at it soon.

**Comment by drdaz** [comment]
So it looks like I unbroke the things again.

But I can't reproduce the macOS test failures happening on the test server locally. Unless I can get more information on what's causing the tests to fail, I can't really do much to fix them :-/

Those logs the tests produce would probably be pretty useful.

**Comment by TomWFox** [comment]
@drdaz how are you running the tests locally?

**Comment by drdaz** [comment]
Both in Xcode and by running the same command the server runs; for macOS `bundle exec rake test:macos`.

I've tried cleaning the project and wiping DerivedData first to simulate a 'clean' run, but no tests fail here.

The macOS tests do respond a little sadly compared to the others when run from the command line; no summary is shown in the console, and it seems like the simulator crashes 7 times on each run... but none of the tests that run fail.

**Comment by TomWFox** [comment]
Bizarre, I feel like there must be a way we can see the test logs. I saw this in the build logs
```
Test session results and logs:
	/Users/distiller/Library/Developer/Xcode/DerivedData/Parse-fhzhwqgymuaowjctjmborcenlkaz/Logs/Test/Test-Parse-macOS-2019.07.10_04-12-54--0700.xcresult
```
And in the config there is this:
```
- store_test_results:
          path: build/reports
```
And in the logs for the upload test results:
```
Archiving the following test results
  * /Users/distiller/project/build/reports

Uploaded 
```

Surely we can see these files or we should be able to change the circles config so that we can?

**Comment by drdaz** [comment]
They're definitely there somewhere :) But how we access them I don't know.

**Comment by drdaz** [comment]
You don't have SSH access to the test machine?

**Comment by TomWFox** [comment]
I don't know but I doubt it's dedicated so its probably all cleared when he build finishes?

**Comment by drdaz** [comment]
Yeah that's quite possible. It does have a step where it spins up an environment.

But it could be that the test code is run (and the results persisted) on something more permanent, while the code being tested is run on a temporary instance. Idk. But I'm sure we can find out :)

I'm not an expert here by any means; haven't really worked with this infrastructure (or the code in this project) before this weekend.

**Comment by drdaz** [comment]
The thing is, when tests fail normally, the it seems failures are specified on CircleCI. Like this: https://circleci.com/gh/parse-community/Parse-SDK-iOS-OSX/2941

The macOS test doesn't do that. So maybe it's failing in a different way (maybe the test fails to run at all). That said, and as I mentioned, running the same tests from the command line locally doesn't show me the results. I've checked manually them using some find + grep-fu.

**Comment by TomWFox** [comment]
I'm wondering whether we might get the logs if we have something like this in the circle config...
```
- store_test_results:
          path: build/reports
- store_artifacts:
    path: build/reports
    destination: test_results
```

**Comment by drdaz** [comment]
Yeah maybe...

Otherwise I'm on the verge of giving this thing a try: https://github.com/artemv/circleci-step-outputter

**Comment by TomWFox** [comment]
Let's see if this works...

**Comment by drdaz** [comment]
So close... that utility would work I think, if only it would recognise it's own command line options. :(

**Comment by drdaz** [comment]
Where would you look for that output? :) From your change I mean. What machine?

**Comment by TomWFox** [comment]
I'm hoping my change will mean the logs show up in the artefacts page on circle, we'll see!

**Comment by drdaz** [comment]
Heh... I actually got that utility to work by copy-pasting the example and modifying.

Unfortunately it just delivers the same text we can see on the server.

**Comment by TomWFox** [comment]
Ok, well the artifacts are sort of working but it's now uploading what I had hoped for.

**Comment by drdaz** [comment]
Yeah it's those diagnostic logs that would help I suspect.

I can't see the artefacts fwiw. Just that they were uploaded somewhere.

**Comment by drdaz** [comment]
This is the difference between the last console output when I run the iOS and macOS tests:

iOS:
Screenshot 2019-07-10 at 18 12 17

macOS:
Screenshot 2019-07-10 at 18 12 57

It's like the layer that presents the tests on the CLI isn't there for the Mac tests. I have no idea where this might be set up.

**Comment by mrmarcsmith** [comment]
I see this fixes the iOS tests! is there anything half baked on the macOS side that couldn't be pulled into master for the sake of at least fixing the iOS tests on master? that way for new PRs we can at least see if all the tests pass on iOS.

**Comment by drdaz** [comment]
@mrmarcsmith I think it's safe to merge, but I don't think I've done anything that fixes the iOS tests here.

As far as I can tell, the iOS tests are unstable; sometimes they work, sometimes they don't. Much as I'd love to take credit for fixing the iOS tests, I fear they're not really fixed 🙂

**Comment by drdaz** [comment]
I have a sneaky feeling that some of these tests fail when the build server builds one branch / pr, followed by a different one.

But I've got no proof yet. Just a hunch.

**Comment by mrmarcsmith** [comment]
Oops! my eyes skipped the “macos” part and I just saw “Fixes tests”. What do you need to put a nail in the coffin for macOS tests? Did you ever get access to those artifacts in CI?

**Comment by drdaz** [comment]
I didn't get access to those things, and I haven't been pushing for them. Been on a long, much needed break.

But yeah this ticket reflects the current state. I need to see more output from the tests to have any clue what's going wrong on the build server - the tests mostly pass locally (also some intermittent failures 🥴), but consistently fail on CI.

As mentioned, there's some difference between the way the macOS tests and all the rest log their output to stdout. Eliminating that difference could possibly show what we need. But I'm not sure where that is configured. Any ideas, @mrmarcsmith?

**Comment by TomWFox** [comment]
I’m happy for this to be merged without the macOS tests passing so we can move forward.

**Comment by drdaz** [comment]
@TomWFox This doesn't fix anything yet. macOS tests don't work, and I don't think it fixes the iOS tests.

**Comment by TomWFox** [comment]
@drdaz my bad, not concentrating, I was thinking this was a different PR.

If you want to investigate the CI stuff further I can ask the others about giving you access.

**Comment by drdaz** [comment]
> @drdaz my bad, not concentrating, I was thinking this was a different PR.
> 
> If you want to investigate the CI stuff further I can ask the others about giving you access.

@TomWFox No worries; I guess you were thinking of #1424 🙂. And yeah... I think it's important a release with the changes in that PR comes soon. I think it could spook users, being unable to install. It would definitely make me look further into the state of the project before using it, while less experienced users might just go elsewhere.

And sure, the more access the better. I'd like to help make the project healthier.

**Comment by TomWFox** [comment]
Let’s work on getting a release together soon - I think I need to get access to the cocoa pod otherwise it won’t deploy.

I’ll ask the other core members about giving you access.

**Comment by TomWFox** [comment]
@drdaz I’ve invited you to the iOS team now so you should get write access to this repo which will hopefully also give you more access to the tests through circle ci

**Comment by drdaz** [comment]
@TomWFox Thanks for the add! I'll try and find some hours in the next week to dig into this again.

**Comment by drdaz** [comment]
Quick update here.

I've used my new Member powers, and got the output from the most recently failed macOS test from CI. The issue seems to be that attempting to set values on the keychain on the test instance fails with this enum from SecBase.h:

 `errSecInteractionNotAllowed              = -25308,    /* User interaction is not allowed. */`.

Sooooo... rights or something. It's the keychain tests that are failing. 

My Googling hasn't turned up anything that looked like the right thing just yet.

Any input welcome. Or I'll pick it up again when I get some time.

**Comment by drdaz** [comment]
[Test-Parse-macOS-2019.09.09_09-32-14--0700.xcresult.zip](https://github.com/parse-community/Parse-SDK-iOS-OSX/files/3592054/Test-Parse-macOS-2019.09.09_09-32-14--0700.xcresult.zip)

This is the test output, should anybody want to poke around.

**Comment by drdaz** [comment]
I couldn't leave it alone.

The macOS tests just passed on CircleCI for the first time. 💪🏼

**Comment by TomWFox** [comment]
Nice, let’s hope it’s consistent!

**Comment by drdaz** [comment]
Yeah... I hope it'll be about as consistent as the iOS / tvOS tests for now 😃

**Comment by drdaz** [comment]
Screenshot 2019-09-10 at 15 57 49
QFT. This actually happened.

**Comment by mrmarcsmith** [comment]
@drdaz amazing! You pulled it off!! Let’s merge this puppy!

**Pull request merged**
