### PR TITLE
Adding OCMock as gitmodule for building tests. 

### PR DESCRIPTION
**Pull request by noobs2ninjas**
For some reason we've never added OCMock as an official dependency in Carthage. It's just automatically loaded because of the Facebook SDK till now.

### CODE REVIEW

**Comment by noobs2ninjas** [comment]
Not sure why its showing every commit. Maybe I did something when merging in upstream master?

**Comment by noobs2ninjas** [comment]
Ok. After this round of tests is complete, the only ones that fail should be due to individual unit tests.

**Comment by drdaz** [comment]
@TomWFox You haven't misunderstood. It's only a dependency for testing / development; the Cartfile defines what the SDK package depends on for users, and they don't want a mock framework in their final product.

While I've never used it this way, one could imagine using a separate Cartfile for development purposes.

The solution we were using before, where OCMock was included as a git submodule is fine imho.

**Comment by noobs2ninjas** [comment]
@drdaz  and @TomWFox 

I agree. Cartfile and Cartfile.resolve updated.

**Comment by TomWFox** [comment]
Seems good to me now. @drdaz are you happy with these changes now?

**Comment by drdaz** [comment]
Not yet :)

The nightly CircleCI deploy still fails. I’ve made a change that should fix that. I removed the chruby commands as a test too; I’m pretty sure I did some similar things on LiveQuery where that change didn’t end up being necessary.

It looks like the twitter_utils test still doesn’t build; it can’t find OCMock. I don’t have a fix handy for that one.

I’m also a little concerned about this PR showing all the commits again. Not sure what it means. 

Reviewing that PR (https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1473) was challenging. I check each change, and try to understand them and their effects, and there’s a lot of stuff in there. I’m thinking that making multiple PRs would have really helped. Actually each subject in the first comment you made in that PR would have been good candidates for PRs themselves 😃:

> Updated carthage to use parse-community/Bolts-ObjC of parse so we can start maintaining Bolts again.
> Updated ParseUI to build in iOS 8 again to fix issues #1434
> Updated to current base internationalism and local to limit depreciation warnings.
> Fixing tvOS builds

They all look about the right 'size'. Smaller, well-defined tasks make happier developers 🙂

**Comment by noobs2ninjas** [comment]
@drdaz I think the other commits showing has to do perhapse with the way I merged upstream/master to catch my fork up. I dont think I failed to squash my last pull request. Either way, this should all get squashed when we push.

Hindsight being 20/20 I completely agree with you about making those individual pull requests. I totally would go back and do it differently if I could. Primarily I wouldn't have insisted that everything(gems, dependencies, xcode version) been 100% caught up. Lots of changes have occurred in so many places between those things that it became such a nightmare to get everything working together again. I wont be in a rush to do this again anytime soon haha. 

Ill get the Twitter test back up and running.  A lot of current issues we've been facing here is that removing OCMock from carthage has changed how we build the unit tests. So, you have to go target by target and update them all.

**Comment by noobs2ninjas** [comment]
@drdaz 

Am trying to get this finished up tonight. Was looking at the nightly builds and unfortunately the change you did back on Jan 18th caused the nightly build to stop working with the following error: 

```
ERROR:  While executing gem ... (Gem::FilePermissionError)
You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
```
Im sorta confused as to why your changes work fine on the individual tests but somehow fail on the nightly build. 
```
nightly:
    jobs:
      - deployment
      - cocoapods:
          requires:
            - deployment
      - carthage:
          requires:
            - deployment
```
Looking at this cocoapods, deployment, and charthage all run *prepare and *defaults. Not sure if this is supposed to have multiple tests for the nightly build but if not then wouldn't this code cause the environment and bundle installation to run multiple times? Thats the only thing I can think of that might be different than normal tests. Either way would you mind taking a look at it?

**Comment by drdaz** [comment]
@noobs2ninjas Hi there! I made that change to fix that error. It's not in mainline yet though, so the nightly builds aren't running that change. When this gets merged, the nightly should stop failing like that.

**Comment by noobs2ninjas** [comment]
@drdaz 

Drp. I feel dumb. I should have known that. I got thrown off because theres no dates its just "1 month ago" and then everything doesnt fit on one page so it looked on my screeen like the nightly build so switching back and forth made it look like it passed and then you did  a commit and it didnt. Didnt hit me it wasnt to master even though im writing this in a PR. lol

**Comment by drdaz** [comment]
Heh no need to be hard on yourself 🙂.

It's a complex business to be in. It gets confusing sometimes.

**Comment by noobs2ninjas** [comment]
@drdaz 
Twitter test just passed. Updated a error response mainly to get all tests running again. So fingers crossed everything should build and anything that doesnt turn green will be from actual non-passing tests.

**Comment by noobs2ninjas** [comment]
@drdaz @TomWFox 

We are a go! Only thing that isn't turning green is from actual failed tests. Not because of build issues.

**Comment by noobs2ninjas** [comment]
I take it back. Travis isnt building but for some reason its from running release.

**Comment by noobs2ninjas** [comment]
@drdaz could you look at the error for me. The errors seem to be from facebook but it doesnt crash till its on twitter.

**Comment by noobs2ninjas** [comment]
Seems like whatever I did worked itself out. I basically removed and added back OCMock which has nothing to do with travis. The error did say "internal error" or something. Either way. It works now. That error did make me realize we need to re-write the travis tests. Seems one does nothing and the other does both jazzy and the release script. Thats for another PR though. I think we are done here!

**Comment by noobs2ninjas** [comment]
@drdaz think I could get your approval?

**Comment by noobs2ninjas** [comment]
@drdaz it would be cool if I could get your approval so I can work on a new issue. I think we will need to update the podspec to pull Bolts from our fork. Not sure how/if we can do that in the podspec. Documentation doesnt mention it although its very possible on podfiles.

**Comment by drdaz** [comment]
Hey there, those iOS tests look funny. I'm not sure I've seen those first 2 errors here before. Can we confirm that these are some of the 'expected' errors for the iOS tests?

I'm not sure about the podspec, since I haven't tried this manoeuvre before, but maybe it's a case of changing the naming in our Bolts podspec, and then matching that in our SDK podspec?

**Comment by noobs2ninjas** [comment]
@TomWFox think i could get you to approve so I can get this done?

**Comment by TomWFox** [comment]
@noobs2ninjas sorry for the delay, I've had a look. It looks like those iOS test failures are relating to OCMock, has the version of OCMock we're using changed?

**Comment by noobs2ninjas** [comment]
@TomWFox Thanks for getting back. Heres the error for each one. 

Twitter:
Failing tests:
	ParseTwitterUtils-Tests:
		-[OAuth1FlowDialogTests testRotation]
** TEST FAILED **

macOS:
Failing tests:
	ParseUnitTests-macOS:
		-[KeyValueCacheTests testConstructors]
		-[PinningObjectStoreTests testFetchPin]
		-[FileControllerTests testDownloadStreamSharesOperations]
** TEST FAILED **

iOS:
Failing tests:
	ParseUnitTests-iOS:
		-[FieldOperationDecoderTests testDecodingAddRelationOperations]
		-[KeyValueCacheTests testConstructors]
		-[PinningObjectStoreTests testFetchPin]
		-[PurchaseControllerTests testBuyProductsAsync]
** TEST FAILED **

As you can see these errors are from failed tests. Which means that the project and OCMock did build successfully or the tests never would have begun. Not sure where you saw OCMock issues, maybe you ended up on a past build page. These however are building just fine. Now I just need to merge this so we can work on fixing the failing tests.

**Comment by TomWFox** [comment]
Continuous Integration and Deployment

**Comment by noobs2ninjas** [comment]
Im guessing it has. OCMock used to be a set version that was a dependency of the Facebook SDK. Facebook has since changed that so I just took whatever version was current when I added it as a git module. My guess is that they switched some of their initializers for OCMStub. Either way though. I think this would fall under the category of fixing the tests which is on my TODO list but a bit beyond the scope of this specific pull request. My only goal was to add OCMock via git module and make sure every test was building. In this case the target did build, its only after the tests have started do we get an error. 

So, can we get this one approved so I can move on to a new PR to fix the tests among other things.

**Comment by drdaz** [comment]
Getting the tests back to the state they were in before all the build environment changes is precisely the point of this PR. The new errors look likely to be a direct result of the changes made to the environment.

I won't approve a PR that adds new test errors to the mix. If the tests can be fixed (or rather the new errors can be eliminated), they can and should be fixed here imho.

**Comment by drdaz** [comment]
lol 🤷🏽‍♂️

**Comment by TomWFox** [comment]
Tbh I’m with @drdaz on this one, I shouldn’t have approved, I just a want to get things moving but really fixing the tests isn’t outside of the scope of this pr.

Is there any practical reason why the tests can’t be fixed in this pr?

**Comment by TomWFox** [comment]
So it looks like we were running OCMock v3.4.3 ([link](https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1473/files#diff-7eba173c347db69674261ade64cfb207L2)) before it was removed.

If there isn't a specific reason to be on a different/newer version, we could try reverting to that version.

**Comment by noobs2ninjas** [comment]
@drdaz @TomWFox 
Unfortunately we cannot add a specific release tag with gitmodules. Another downside to not using Carthage, but we are here now so this is what we're working with. 

My PR title is exactly what I meant "Adding OCMock as gitmodule for building tests." We had failing tests before this so I had a two step plan. First was to get all tests building in this PR. The second PR is to fix tests. 

I looked into it and this error has been there since the last time we updated facebook. So whatever version they updated to wasn't working either before they removed OCMock entirely. In fact before I even started contributing there where failed iOS tests. In other words fixing the OCMock errors will still leave us with failed tests regardless. Not to mention macOS and twitter each have their own errors to fix as well that have nothing to do with this. 

My thinking was, as mentioned previously by @drdaz, this PR is already a bit out of bounds of what the title says. Also, fixing all builds across all targets would constitute its own PR. However, if you guys really would like me to I will go dig through the documentation and fix the errors. Just remember, iOS still had failing tests before this change.

**Comment by noobs2ninjas** [comment]
Ill do this while I await your response. Ill go in and see if there is an easy fix for the errors we have without having to go back through their changelogs and documentation.

**Comment by noobs2ninjas** [comment]
Ok, so I took a look into it. Turns out that error occurs from and exception thrown in the test itself. So, that error is just hiding a failed test underneath. 

Heres what Circle Says:
```
PurchaseControllerTests
  testBuyProductsAsync, failed: caught "NSInternalInconsistencyException", "Mock object was not used in OCMStub/OCMExpect/OCMReject. Did you accidentally use a real object?"
  /Users/distiller/project/Parse/Tests/Unit/PurchaseControllerTests.m:191

    OCMStub([purchaseController canPurchase]).andReturn(YES);
    XCTestExpectation *failInvalidProductExpectation = [self expectationWithDescription:@"Failed Invalid Product"];


	 Executed 815 tests, with 4 failures (1 unexpected) in 26.993 (27.481) seconds

2020-03-06 09:49:35.752 xcodebuild[5158:16524] [MT] IDETestOperationsObserverDebug: 258.396 elapsed -- Testing started completed.
2020-03-06 09:49:35.752 xcodebuild[5158:16524] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2020-03-06 09:49:35.753 xcodebuild[5158:16524] [MT] IDETestOperationsObserverDebug: 258.396 sec, +258.396 sec -- end
Failing tests:
	ParseUnitTests-iOS:
		-[FieldOperationDecoderTests testDecodingAddRelationOperations]
		-[KeyValueCacheTests testConstructors]
		-[PinningObjectStoreTests testFetchPin]
		-[PurchaseControllerTests testBuyProductsAsync]

** TEST FAILED **
```

Heres the actual error when ran in Xcode.

```
2020-03-08 18:46:08.447498-0500 ParseUnitTests-iOS-host[5130:86650] Launching with XCTest injected. Preparing to run tests.
2020-03-08 18:46:08.654189-0500 ParseUnitTests-iOS-host[5130:86650] Waiting to run tests until the app finishes launching.
Test Suite 'Selected tests' started at 2020-03-08 18:46:08.909
Test Suite 'ParseUnitTests-iOS.xctest' started at 2020-03-08 18:46:08.910
Test Suite 'PurchaseControllerTests' started at 2020-03-08 18:46:08.911
Test Case '-[PurchaseControllerTests testBuyProductsAsync]' started.
/Users/nathankellert/Desktop/Parse-SDK-iOS-OSX/Parse/Tests/Unit/PurchaseControllerTests.m:191: error: -[PurchaseControllerTests testBuyProductsAsync] : failed: caught "NSInternalInconsistencyException", "Mock object was not used in OCMStub/OCMExpect/OCMReject. Did you accidentally use a real object?"
(
    0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
    1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
    2   CoreFoundation                      0x00007fff23c710bc +[NSException raise:format:] + 188
    3   OCMock                              0x000000010a09deda +[OCMMacroState endStubMacro] + 826
    4   ParseUnitTests-iOS                  0x00000001093e67fe -[PurchaseControllerTests testBuyProductsAsync] + 10414
    5   CoreFoundation                      0x00007fff23c7820c __invoking___ + 140
    6   CoreFoundation                      0x00007fff23c753af -[NSInvocation invoke] + 319
    7   XCTest                              0x0000000104fc7821 __24-[XCTestCase invokeTest]_block_invoke.208 + 78
    8   XCTest                              0x00000001050219b9 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 57
    9   XCTest                              0x00000001050218d7 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 96
    10  XCTest                              0x0000000104fc730a __24-[XCTestCase invokeTest]_block_invoke + 1153
    11  XCTest                              0x0000000104fc6de2 -[XCTestCase testContextPerformInScope:] + 211
    12  XCTest                              0x0000000104fc6e7c -[XCTestCase invokeTest] + 137
    13  XCTest                              0x0000000104fc8bed __26-[XCTestCase performTest:]_block_invoke_2 + 43
    14  XCTest                              0x00000001050219b9 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 57
    15  XCTest                              0x00000001050218d7 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 96
    16  XCTest                              0x0000000104fc8b04 __26-[XCTestCase performTest:]_block_invoke.334 + 88
    17  XCTest                              0x0000000105035302 +[XCTContext runInContextForTestCase:block:] + 219
    18  XCTest                              0x0000000104fc8273 -[XCTestCase performTest:] + 668
    19  XCTest                              0x000000010500d807 -[XCTest runTest] + 57
    20  XCTest                              0x0000000104fc284a __27-[XCTestSuite performTest:]_block_invoke + 365
    21  XCTest                              0x0000000104fc1f74 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 54
    22  XCTest                              0x0000000104fc2271 -[XCTestSuite performTest:] + 355
    23  XCTest                              0x000000010500d807 -[XCTest runTest] + 57
    24  XCTest                              0x0000000104fc284a __27-[XCTestSuite performTest:]_block_invoke + 365
    25  XCTest                              0x0000000104fc1f74 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 54
    26  XCTest                              0x0000000104fc2271 -[XCTestSuite performTest:] + 355
    27  XCTest                              0x000000010500d807 -[XCTest runTest] + 57
    28  XCTest                              0x0000000104fc284a __27-[XCTestSuite performTest:]_block_invoke + 365
    29  XCTest                              0x0000000104fc1f74 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 54
    30  XCTest                              0x0000000104fc2271 -[XCTestSuite performTest:] + 355
    31  XCTest                              0x000000010500d807 -[XCTest runTest] + 57
    32  XCTest                              0x000000010504428e __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 171
    33  XCTest                              0x0000000105044391 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.84 + 118
    34  XCTest                              0x0000000104fdc593 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 588
    35  XCTest                              0x000000010504404d -[XCTTestRunSession runTestsAndReturnError:] + 623
    36  XCTest                              0x0000000104fa5dd7 -[XCTestDriver runTestsAndReturnError:] + 456
    37  XCTest                              0x0000000105031554 _XCTestMain + 2484
    38  libXCTestBundleInject.dylib         0x0000000104d6cbe7 __copy_helper_block_e8_32s + 0
    39  CoreFoundation                      0x00007fff23bd429c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
    40  CoreFoundation                      0x00007fff23bd3a08 __CFRunLoopDoBlocks + 312
    41  CoreFoundation                      0x00007fff23bce894 __CFRunLoopRun + 1284
    42  CoreFoundation                      0x00007fff23bce066 CFRunLoopRunSpecific + 438
    43  GraphicsServices                    0x00007fff384c0bb0 GSEventRunModal + 65
    44  UIKitCore                           0x00007fff48092d4d UIApplicationMain + 1621
    45  ParseUnitTests-iOS-host             0x0000000103fdcf02 main + 162
    46  libdyld.dylib                       0x00007fff5227ec25 start + 1
    47  ???                                 0x0000000000000005 0x0 + 5
)
Test Case '-[PurchaseControllerTests testBuyProductsAsync]' failed (0.713 seconds).
Test Suite 'PurchaseControllerTests' failed at 2020-03-08 18:46:09.630.
     Executed 1 test, with 1 failure (1 unexpected) in 0.713 (0.719) seconds
Test Suite 'ParseUnitTests-iOS.xctest' failed at 2020-03-08 18:46:09.630.
     Executed 1 test, with 1 failure (1 unexpected) in 0.713 (0.720) seconds
Test Suite 'Selected tests' failed at 2020-03-08 18:46:09.631.
     Executed 1 test, with 1 failure (1 unexpected) in 0.713 (0.722) seconds
```

Since this was ran within Xcode it eliminates OCMock as the culprit. So, I’d like to ask again. Can I please get to looking at the fixes in another pull request. Really I just want to get this merged, which fixes all builds and restores our nightly build. Then I can forget about all of this stuff and focus on fixing tests.

**Comment by noobs2ninjas** [comment]
Also its worth mentioning that there where 3 other tests that failed in the iOS unit tests.

**Comment by noobs2ninjas** [comment]
@TomWFox unfortunately one of the downsides to using gitmodules is it doesn't allow for designating a release. However, these failed tests have been failing well before the last version. They where failing before I even started changing thing. They failed when facebook was the one who included OCMock. The only thing that OCMock has changed is rather than just failing the test, they now create their own exception with a more detailed explanation. In fact, when 3.0 came out YEARS ago, they made changes that would have required you to convert all your objects to OCMockObjects which is the error we got. So, it seems they are just making their errors more visible. Even after fixing that error I had 3 more tests fail. 

Anyway, earlier I had had commented and complained about some of these being here for so long and how it wasn't my update that even broke them. Well, I got bored and started fixing things. So heres where we stand now.  I fixed testConstructors, testFindObjectsCacheOnlyCorruptJSON, testDownloadStreamSharesOperations, and testBuyProductsAsync. So, all test but testFetchPin, and testFetchPinCaching. 

The odd thing about these tests is that they BOTH succeed sometimes and they always succeed if you run them individually. Other times one fails and the other doesnt. Sometimes I get registered subclass errors. Sometimes I get 'The class PFPin must be registered with registerSubclass before using Parse.' or unrecognized selector.  Other times it straight up crashes with no exception. What I suspect is that other tests can change the environment and setup these tests to fail. Which would make sense as to why they succeed when ran individually. It would also explain the randomness because these tests aren't necessarily ran in order. Also, it may not even be the tests themselves as we have issues about offline pinning.

So, I was hoping that the tests I've fixed for now will suffice as these two tests definitely have some underlying issues than simply the individual tests themselves. I worked on them for an hour and still got no better results. In fact both tests passed. Then failed on Circle and then failed afterwards again on my computer and I have no clue why. 

@drdaz not sure how well you know the testing setup. I have a suspicion we have a offline storage issue and also if you have any knowledge of the unit testing. I see classes like PFStrictProtocolMock and PFStrictClass mock etc.. but OCMock for a while now requires using OCObjectMock and OCProtocol mock. So it seems we are mocking things twice. Anyway, thats a whole issue in itself is cleaning everything up to make things more efficient and cleaner. Just was hoping you might be able to save me some time and also help me dig down to the bottom of the pin issues.

**Comment by drdaz** [comment]
If you've fixed those janky tests, that would be awesome!

`However, these failed tests have been failing well before the last version. They where failing before I even started changing thing.`

Link?

`@drdaz not sure how well you know the testing setup. I have a suspicion we have a offline storage issue and also if you have any knowledge of the unit testing.`

I haven't dug into how offline storage works really. Some years ago it burned me badly as a user of the SDK. I haven't felt like messing with it since.

**Comment by drdaz** [comment]
Wait, looks like the OCMock failures were already fixed? This looks good!👌🏼

I committed blindly. If it breaks anything, we roll it back.

Any idea about these warnings?

> Multiple targets match implicit dependency for product reference 'OCMock.framework'. Consider adding an explicit dependency on the intended target to resolve this ambiguity. (in target 'ParseUnitTests-iOS' from project 'Parse')
>     Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the ParseUnitTests-iOS-host editor. (in target 'ParseUnitTests-iOS-host' from project 'Parse')

It's in multiple projects. We've seen this one cause build failures before.

**Comment by noobs2ninjas** [comment]
@drdaz Yup! I did a bunch of complaining. Then i deleted those comments and decided to go ahead and fix it. 

> It's in multiple projects. We've seen this one cause build failures before.

Yea its weird. I ran the build dozens of times and it never failed. It should be easy to fix a lot of the warnings. They all have to do with linking dynamic frameworks. We have lots of warnings based around the same issue. To get those cleaned up I'll have to remove all dependencies from every target and dynamic target and relink everything in a uniform way. It's not hard. Just a bit time consuming and tedious. For now I'm not worried about us having any issues with it.

**Comment by noobs2ninjas** [comment]
Just waiting approval and we should be good.

**Comment by drdaz** [comment]
Great work! 🙏🏼👌🏼

**Pull request merged**
