### PR TITLE
ci: Fix manual documentation publishing workflow

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Issue Description

Dependencies used to generate docs are missing.

Screen Shot 2023-03-07 at 12 06 02 PM

Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1702

### Approach

* Install carthage submodules
* Remove the dependency on `parseui` test suite to generate docs.

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good, let's try it out...

**Comment by mtrezza** [comment]
It seems there is still an [issue](https://github.com/parse-community/Parse-SDK-iOS-OSX/actions/runs/4358837840/jobs/7619917284):

```
[INFO] copy /Users/runner/work/Parse-SDK-iOS-OSX/Parse-SDK-iOS-OSX/docs to /Users/runner/actions_github_pages_1678225778587
  cp: no such file or directory: /Users/runner/work/Parse-SDK-iOS-OSX/Parse-SDK-iOS-OSX/docs/*
  cp: no such file or directory: /Users/runner/work/Parse-SDK-iOS-OSX/Parse-SDK-iOS-OSX/docs/.*
```

Could the path be incorrect, because it contains two times `Parse-SDK-iOS-OSX`?

**Comment by dplewis** [comment]
@mtrezza i opened a PR for that

https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1721

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.2.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/2.2.0)

**Pull request merged**
