### PR TITLE
Allowing to re-save installation if LDS is enabled

### PR DESCRIPTION
**Pull request by hermanliang**
Related Issue
ParsePlatform/Parse-SDK-Android#605: Re-save installation is allowed if LDS is enabled 

Related PR
ParsePlatform/Parse-SDK-Android#607: Re-save installation is allowed if LDS is enabled 
ParsePlatform/Parse-SDK-Android#611: Not allowing setObjectId() in ParseInstallation

In this PR
1. `setObjectId` is not allowed in `PFInstallation` for safety purpose.
2. If installation is removed on the server, the installation data will attempt to resave even if LDS is enabled.

@rogerhu

### CODE REVIEW

**Comment by rogerhu** [comment]
@flovilmart

**Comment by flovilmart** [comment]
Should we add tests for that? Seems dangerous to add this behaviour without corresponding tests.

**Comment by hermanliang** [comment]
@flovilmart related unit test is added
Thanks

**Comment by hermanliang** [comment]
@flovilmart I think it's okay to merge now. Thanks!

**Comment by hermanliang** [comment]
@flovilmart can you help me merge this PR, since I'm not permitted to merge in this repo.
Thanks :)

**Comment by flovilmart** [comment]
Sorry, didn't see your previous comment!

**Comment by hermanliang** [comment]
No worries. Thanks!

**Pull request merged**
