### PR TITLE
Updates xcbuildtools submodule

### PR DESCRIPTION
**Pull request by drdaz**
My syntax was off in the last submodule update. Hopefully this is kosher.

### CODE REVIEW

**Comment by drdaz** [comment]
@flovilmart I've persuaded the travis-ci build to succeed, even though I don't quite understand why the plain iOS destination works (not TV or Watch). It still doesn't specify an OS to use. 🤷🏼‍♂️

In doing this I also downgraded the WatchOS version of the destination to 4.2, since there was no destination offering WatchOS 5.0 as was specified in build_framework_task.rb.

I'm not entirely sure where to create these destinations (all are currently specified with last years' OS'), and I really wanted a green light. I wasn't planning on spending my whole afternoon on this and needed a taste of success, so I proceeded with last years' OS versions, rather than find out how to create new modern destinations :)

The macOS and twitter_utils tests fail intermittently (seems to be every other build) here with an inability to find some Bolts headers.

**Comment by flovilmart** [comment]
The problem with bolts headers / framwork / link is actually a big one. 

The build system can’t sometimes by himself infer which flavor of Bolts (static, dynamic...) to link against as they all share the same name, bundle name etc....

This begs a better / more profound investigation. 

For the current year’s version, it depends if we test against Xcode 10 or Xcode 9. I’m not sure.

**Comment by flovilmart** [comment]
@drdaz, if you want to put some time on it, we are looking for a maintainer for this repo. Mostly, the most pressing issue is to smoothly work on the Xcode 10 compat. Is it something you’re willing to explore?

**Comment by brianyyz** [comment]
@flovilmart For folks like me who have less experience in this area can you provide a pointer to what the role of maintainer entails? I think there are people in this community who might step up if they had a better understanding of what is involved - again speaking for me :-)

**Comment by flovilmart** [comment]
Maintainers is first and foremost responsible for very few things. Most of all, being guarant of the code of conduct, reviewing (if possible) and pushing changes while keeping in mind the needs of the community.

As a maintainer, I didn’t had much time to develop new features, but I attempted to maintain as much as I could (until now).

The last thing, before giving the commit access, is a certain level of commitment towards this project. Helping others, triaging / closing issues, opening Pr are a pre requisite before I can, with a certain peace of mind, grant those accesses.

**Comment by drdaz** [comment]
@flovilmart You know I'd been giving it some thought since I saw the project needed maintainers / help. I've been getting a lot of value from the parse projects these past couple of years, and I'd really like to give back. 

But I've got to be completely honest with myself and the project; *right now* it would be a bad move for me to commit to more projects. I'm working on 3 projects atm, 2 of which are at the early startup stage. I just don't feel I can guarantee the time needed to do this right.

In a few months this could be a very different story. In the mean time I'm happy to try and help where I can.

**Comment by drdaz** [comment]
... with all that said it could be useful to know what the issue is with Xcode 10 right now, for anybody who wants to help ;)

I'm able to build this project consistently with Xcode 10 using CocoaPods, and with the small changes I added, with Carthage too. Isn't this 'just' an issue with the CI / test build process?

**Pull request merged**
