### PR TITLE
docs: Fix jazzy undocumented symbols

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Issue Description

There are a lot of errors when generating docs that prevents symbols from being documented.
https://github.com/parse-community/Parse-SDK-iOS-OSX/actions/runs/11596782336/job/32288646411
```
error: 'BFTask.h' file not found
error: module 'Bolts' not found
```

Before
Screenshot 2024-10-30 at 3 02 03 PM

After
Screenshot 2024-10-30 at 4 45 43 PM

### Approach

* Move `@import Bolts` to `.m` and add `@class` to `.h`
* Remove duplicate properties like `dataAvailable` from catetories
* Add missing imports for Constants
* Properly handle Bolts import
* Remove old carthage/pods imports
* Remove console errors

### TODOs before merging

- [x] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Review by mtrezza — COMMENTED** [review]
Why are the tests failing

**Comment by dplewis** [comment]
@mtrezza For some reason functions that return BFTask can't be called in swift after this change.

```
+ (nonnull BFTask<NSNumber *> *)trackEvent:(nonnull NSString *)name;
```
```
class func trackEvent(_ name: String) -> BFTask
```

**Comment by dplewis** [comment]
@mtrezza I found a cleaner way to do this, simple refactoring

**Comment by mtrezza** [comment]
The build worked in the PR last week, so I assume its this PR that breaks it?

**Comment by mtrezza** [comment]
Turns out the CI is also flaky in that other PR. So I'll just rerun the CI here until hopefully all passes.

**Comment by mtrezza** [comment]
@dplewis I couldn't get the CI to pass, even after re-running the failed tests multiple times. What should we do here?

**Comment by dplewis** [comment]
I closed this, can you do a release PR? The Xcode 16 support got added. If that PR has flaky test then I don’t know what to do

**Comment by mtrezza** [comment]
Are the changes in https://github.com/parse-community/Parse-SDK-iOS-OSX/commit/0be6870d805c0cb3b89befdaecb15b08d30e150d necessary to use the SDK in Xcode 16? I assumed it only added the Xcode 16 tests to the CI and the gemfile dependency upgrades were done additionally but not required for Xcode 16?

**Comment by dplewis** [comment]
Just a suggestion if you want to update the change log then a release would be nice. A patch release would work as no functionality has changed.

**Comment by mtrezza** [comment]
We'd only do a changelog entry if there are changes in a PR that allows for a certain functionality. As I understand it, there are no changes in https://github.com/parse-community/Parse-SDK-iOS-OSX/commit/0be6870d805c0cb3b89befdaecb15b08d30e150d that would be necessary to use the Parse SDK in Xcode 16, we only added the CI test for it, right?

**Pull request closed without merging**
