### PR TITLE
FBSDK change from 5.x to 6.x

### PR DESCRIPTION
**Pull request by markuswinkler**
FBSDK change from 5.x to 6.x

### CODE REVIEW

**Comment by TomWFox** [comment]
Thanks, we’ve got a few failed tests but they are the usual culprits.

**Comment by markuswinkler** [comment]
I didn't change anything besides the FBSDK reference 😅

**Comment by TomWFox** [comment]
The Cartfile also needs updating.

**Comment by markuswinkler** [comment]
Oops. Done.

**Comment by drdaz** [comment]
There's a script that needs updating in the Parse project file too. I'll try and look at it later today.

**Comment by drdaz** [comment]
No script update needed. We've been downloading and linking version 6 since it was released for the static builds (it downloads the latest)... lucky there were no breaking API changes for us with this release 🙂.

**Pull request merged**
