### PR TITLE
updated demo - extension login function "log"

### PR DESCRIPTION
**Pull request by TigPT**

### CODE REVIEW

**Comment by flovilmart** [comment]
@TigPT Thanks for the PR, however it reads weirdly in Swift. Do you think we can get a better swift refined name in there so we keep the original name?

**Comment by flovilmart** [comment]
@TigPT ping?

**Comment by TigPT** [comment]
@flovilmart I was on vacations with family, let me get back on my backlog and I will get into this soon. I want to dig more into swift but its just a hobby for now.

I like that you are trying to make me engage with this git to help you push forward and I thankful. I will be back on this soon. Ty.

**Comment by flovilmart** [comment]
No problem! Take your time :)

**Pull request closed without merging**
