### PR TITLE
feat: Remove `ParseUI`

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Issue Description

Building a UI has become a lot easier over the years, especially with SwiftUI; ParseUI today looks like an obsolete convenience that could be dropped from the Parse SDK. This is a breaking change.

Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1760
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1729
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1493
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1406
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1517

### Approach

Remove ParseUI.

### TODOs before merging

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] Remove CI job

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]

**Comment by dplewis** [comment]
@mtrezza Codecov is broken

**Review by JohnCaccavale — APPROVED** [review]

**Comment by JohnCaccavale** [comment]
Have the Privacy Manifests been added to the project yet? Worth including them here with this PR or best to do that in a separate PR?

**Comment by dplewis** [comment]
> Have the Privacy Manifests been added to the project yet? Worth including them here with this PR or best to do that in a separate PR?

They haven't been added. Can you open an issue for it? I need to do some research on it.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/4.0.0)

**Pull request merged**
