### PR TITLE
Fixing CircleCI and Travis builds. 

### PR DESCRIPTION
**Pull request by noobs2ninjas**
- Updated carthage to use [parse-community/Bolts-ObjC](https://github.com/parse-community/Bolts-ObjC) of parse so we can start maintaining Bolts again.
- Updated ParseUI to build in iOS 8 again to fix issues #1434
- Updated to current base internationalism and local to limit depreciation warnings. 
- Fixing tvOS builds

### CODE REVIEW

**Comment by noobs2ninjas** [comment]
I know this will fail. We need to do a release on Bolts to really get this working but I wanted this hear so that I can test our build and make adjustments as we update bolts.

**Comment by noobs2ninjas** [comment]
God I hate the fact that Xcode environment renames all simulators every 2 updates.

**Comment by noobs2ninjas** [comment]
Finally!

**Comment by noobs2ninjas** [comment]
@drdaz did you want to review changes or should I just push it on through?

I think I finally got everything figured out and got it done. Updated to Xcode 13.2.1. Working off the Bolts-ObjC fork. Updated submodules(xctoolchain was a pain). Fixed Travis issues. CircleCI builds and the only thing failing is unit tests. Also, got the catalyst mess figured out that screwed everything up when we updated with all the framework name ambiguity and the poor separation between platform targets because of it.  

Only took me 2000 commits to figure everything out! Good news is that I feel I kinda got the hang of this now. Now I think we do need to do some Catalyst specific testing to improve compatibility but right now I just want to get a release out and get everything back on track.

Edit: Nevermind. Have to wait until xctoolchain is updated again because Travis doesnt update their documentation.

**Comment by drdaz** [comment]
I'm a confused why you merged this to master? None of the tests aside from CI seem to have been working here??

**Comment by noobs2ninjas** [comment]
Because all the tests BUILD. The only reason things are failing now is due
to failed unit tests. Which means my this pull request did it’s job.

**Comment by noobs2ninjas** [comment]
Oh I get what you are pointing at. No I canceled those builds because it
takes forever for them to run and it takes away from other repos trying to
run since we can only have 1 building concurrently. I merged without
approval so you could catch up to master. So yea. Shows failed because I
canceled.

**Comment by noobs2ninjas** [comment]
@drdaz 

I think we are not understanding each other. Something must have happened with my merge. The last things I did with the CircleCI build had every single test building(with the exception of nightly builds). I did continue to make changes but nothing I thought had anything to do with CircleCI. 

 I guess I should have gone back and let it all run after I fixed travis. You are right and thats my bad. I'll take a look and get it fixed. Dang, I was so positive everything was still building I didnt even think about it.

**Comment by noobs2ninjas** [comment]
Also, I'll do better in the future with approval. Thats my bad.

**Comment by noobs2ninjas** [comment]
@drdaz 
Ok. I figured out what messed it up. Turns out we've never had OCMock as a dependency. For some weird reason the Facebook SDK has it required and thats the only reason its been loading up till now. Right before I merged I updated the facebook SDK version and guess what!? The facebook SDK no longer requires OCMock...so Carthage stopped loading it in the tests.  So thats why it all stopped failing all at once.

**Comment by TomWFox** [comment]
I'm wondering whether it might be best to add branch protection on master to require at least one review, just so there is no confusion in future, I'm not pointing fingers - I've merged without review in the past but I've come to see how important the review process is.

Thoughts?

**Comment by drdaz** [comment]
@TomWFox I'm 100% behind that idea. It's a useful rule, and we may as well enforce it.

**Comment by drdaz** [comment]
FWIW I'd recommend reverting the merge to master and taking a proper look at this.

We can still safely do that since there haven't been any commits to master since.

**Pull request merged**
