### PR TITLE
Release 1.19.0

### PR DESCRIPTION
**Pull request by drdaz**

### CODE REVIEW

**Comment by drdaz** [comment]
@cbaker6 I just merged a PR to master, and the docs build timed out during bundle install. That sasc dependency takes a while... is there somewhere we can increase the timeout?

**Comment by cbaker6** [comment]
I believe there is, I'm about to make a PR to your branch increasing the timeout of this test and the other ones that failed recently.

Should have it finished in a few minutes.

**Comment by drdaz** [comment]
Nice. But I don't think those changes will fix this. Because they don't contain the number 10. Here's how the docs target failed:

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

**Comment by cbaker6** [comment]
I see, that's a travis issue. Did you update the gem files? It looks like it didn't access the cache.

I'm looking into an update now

**Comment by drdaz** [comment]
It does look like a travis thing. With this funky workaround:

https://github.com/travis-ci/travis-ci/issues/4190#issuecomment-353342526

**Comment by drdaz** [comment]
> Did you update the gem files?

Not that I know of...

**Comment by cbaker6** [comment]
The update I added may fix the problem, as `travis_wait` seems to do something similar to the link you sent by outputting something to the logs every minute to prevent timeouts.

**Comment by cbaker6** [comment]
I think I fixed the travis error by letting travis handle `bundle install`. The way it was written before was overriding travis auto command for `bundle install` which might be why there was always a cache miss.

You should be good to go...

**Comment by drdaz** [comment]
So I was following the instructions in the README for updating the version number: bundle exec rake package:set_version[X.X.X]. I've tried a few interpretations of that text (some with spaces, some with brackets) and they all fail. It also looks like we might have changed the way we handle version numbers - the script replaces $MARKETING_VERSION with a concrete number (for me, consistently 1.18.0, since it doesn't like the way I provide the args) in several files.

@TomWFox do you know anything about this? 

(Moved this comment to this thread, since it belongs here.)

**Comment by drdaz** [comment]
I just did a search and replace on the version number to update. Feels like that number should be saved in far fewer places.

**Comment by drdaz** [comment]
The last commit rolls back some changes made during the last release to the way we store version numbers. They added misdirection, but I don't understand what value they added.

The version number update script *does* still work. But using zsh you need to escape the command. I've updated the README accordingly.

**Comment by drdaz** [comment]
@cbaker6 So bundle install is still timing out. I have a feeling you were on the right track with https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1538/commits/57ccfd3c7284c16c712a03043b66a5183e43e868

**Comment by drdaz** [comment]
> I think I fixed the travis error by letting travis handle `bundle install`. The way it was written before was overriding travis auto command for `bundle install` which might be why there was always a cache miss.
> 
> You should be good to go...

Maybe I'm reading this wrong, but it looks like the docs build that succeeded on that commit might have used the cache:
https://travis-ci.org/github/parse-community/Parse-SDK-iOS-OSX/jobs/722517936. I don't see the output from `bundle install`.

**Comment by drdaz** [comment]
Umm... it sort of looks like travis_wait [doesn't work for us](https://travis-ci.org/github/parse-community/Parse-SDK-iOS-OSX/jobs/722772328).

**Comment by cbaker6** [comment]
> @cbaker6 So bundle install is still timing out on travis. I have a feeling you were on the right track with 57ccfd3

Yup, this should work, since the commit with letting travis handle bundle install didn't

**Comment by drdaz** [comment]
How can we tell if your cache is being used? Do the build times look right to you?

**Comment by cbaker6** [comment]
> Maybe I'm reading this wrong, but it looks like the docs build that succeeded on that commit might have used the cache:
https://travis-ci.org/github/parse-community/Parse-SDK-iOS-OSX/jobs/722517936. I don't see the output from bundle install.

The one on the master didn't complete, so it won't show. To tell if it used the cache correctly, the time should be reduced. `bundle install` takes ~300s or 5 minutes from looking at the logs, so that time should be shortened (I'm guessing to 1 minute or less). When I added cache to circle, the time change was significant. For some reason, travis saves the cache, but is not using it.

**Comment by drdaz** [comment]
Output from current build:

```
Setting up build cache
103$ export CASHER_DIR=${TRAVIS_HOME}/.casher
1040.16s$ Installing caching utilities
1050.01s4.17sattempting to download cache archive
106fetching PR.1538/cache--osx-xcode11.6-39b89be44f4c2a7779f4f272f4244ebc7a58c3f996006360ff5e74555c66ae5b--rvm-default--gemfile-Gemfile.tgz
107fetching PR.1538/cache-osx-xcode11.6-39b89be44f4c2a7779f4f272f4244ebc7a58c3f996006360ff5e74555c66ae5b--rvm-default--gemfile-Gemfile.tgz
108fetching PR.1538/cache--rvm-default--gemfile-Gemfile.tgz
109fetching master/cache--osx-xcode11.6-39b89be44f4c2a7779f4f272f4244ebc7a58c3f996006360ff5e74555c66ae5b--rvm-default--gemfile-Gemfile.tgz
110found cache
1110.01s3.50sadding /Users/travis/build/parse-community/Parse-SDK-iOS-OSX/bundle to cache
112creating directory /Users/travis/build/parse-community/Parse-SDK-iOS-OSX/bundle
```

This is hidden in the logs - you have to expand it. Not sure if you've seen it.

**Comment by cbaker6** [comment]
> This is hidden in the logs - you have to expand it. Not sure if you've seen it.

Yup, I've seen it, that's how I know travis is saving/restoring the cache, but bundle still goes through it's typical install which is why I'm saying it's not hitting the cache

**Comment by cbaker6** [comment]
Circle still takes a little longer than travis because of `Carthage` so having a longer travis (no cache hit) isn't much of an issue.

**Comment by drdaz** [comment]
Sure. I just figured since my attention is here, if it was just a couple of pokes away, we could get it working.

> If it was hitting cache, those timeouts during bundle install would never happen and bundle install would complete in a few seconds (like how it completes now in the circle logs)

Yeah ok, it's still taking a good 5 mins. Ahh well.

**Comment by cbaker6** [comment]
> Sure. I just figured since my attention is here, if it was just a couple of pokes away, maybe we could get it working 🙂.

My guess is this is an issue from travis's side. I think the cache is setup correctly, and if so, once they fix it, it will start hitting the cache. When it does, we "might" be able move `Carthage` to travis. We I did in my previous PR was move some tests around to shorten is much as possible at the time. Ideally, we will want to move tests around to get travis and circle to finish around the same time, but that time be the shortest amount of minutes.

**Comment by cbaker6** [comment]
One thing that might be possible is since travis has most of the gems install from the gem file already, skip bundle install entirely in travis, and use the native installs. This will speed up time significantly in travis if it works.

The only thing that would need to be installed is jazzy and it's dependencies for docs

**Comment by cbaker6** [comment]
So the last PR might work as that gem file seems to only be related to "jazzy" and it's dependencies. travis comes with `rake` and `cocoapods` so one thing to be mindful of is updating `osx_image: xcode11.6` in the future. travis typically installs the latest version of rake and cocoapods in it's newer Xcode builds, so if the project ever becomes incompatible with one of those we will run into build errors (these can be resolved by adding back bundle install to use the gem file).

The other thing to be mindful of is if the gem file isn't up-to-date, circle and travis maybe building with slightly different versions. Not too big of a problem IMO as they are building/testing different things. 

Depending on how much the travis time shrinks now, we might be able to move a build from circle to travis

**Comment by drdaz** [comment]
>  if the project ever becomes incompatible with one of those we will run into build errors (these can be resolved by adding back bundle install to use the gem file).
> 

This seems like something there should be a note about somewhere, so that when it happens, it doesn't take hours to figure out what happened.

> The other thing to be mindful of is if the gem file isn't up-to-date, circle and travis maybe building with slightly different versions. 

Potential for different build environments triggers my PTSD 😬. But surely both environments are building from the same source? So the same gemfile + lock?

**Comment by cbaker6** [comment]
> Potential for different build environments triggers my PTSD 😬. But surely both environments are building from the same source? So the same gemfile + lock?

Yes on the same source... As for the same lock file, it's only used when `bundle install` occurs, so this is for `jazzy` in travis, and all of the parse builds in circle. The reason for the need of `bundle install` in circle is it doesn't seem to come with as much pre-installed gems as circle.

The rest of the builds in travis are using what travis has preinstalled currently. If you want them to use the same, we would need to add back `bundle install` which would increase the time again

**Comment by cbaker6** [comment]
I don't think the builds will to much better than ~50 minutes using both travis and circle with the current resources, so I switched back

**Comment by drdaz** [comment]
Our coverage dropped from 76% to 5.5% with these changes, according to codecov. This comes as a surprise.

**Comment by cbaker6** [comment]
I think it's just not reporting correctly, give me a sec...

**Comment by drdaz** [comment]
Oh these random test fails are pretty annoying...

**Comment by drdaz** [comment]
Okay now it's just holding a grudge. Seems like codecov's results on retry don't override previous attempts. Maybe there's a fix for this behaviour, but I feel like this needs to be released.

I'm cool with merging and tagging this if you are. Needs an approval.

**Comment by natekellert** [comment]
Just was checking into see how everything is going around here. Its been a little while. Saw this PR and read the comments. I Hate to be the bearer of bad news. You guys might have looked at what my open PR changes as it fixed a lot of this and did it in about 20 min faster and thats with doing a test cocoapod build. 

There are two issues that these keep happening. There is an issue with cocoapods 1.8.4 and macOS 10.16 that left cocoapods running in the background even after all pods are installed causing even a real mac to time out. So, it wasn't just a travis thing. So, I moved to 1.9.3 and 10.15 and presto everything works and builds faster. @drdaz you where actually the one who gave me the info to find the fix lol.  Unfortunately the changes you made are actually slowing the jobs down at this point. Besides just extra unnecessary tasks, you didn't override the global install or at least instruct travis to skip install to use only the job install, some things are now likely running twice. Anyway, wish I would have checked in sooner to save everyone some time. Feel free to check this out for a reference to [my changes](https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1518).

**Comment by drdaz** [comment]
> Just was checking into see how everything is going around here. Its been a little while. Saw this PR and read the comments. I Hate to be the bearer of bad news. You guys might have looked at what my open PR changes as it fixed a lot of this and did it in about 20 min faster and thats with doing a test cocoapod build.
> 
> There are two issues that these keep happening. There is an issue with cocoapods 1.8.4 and macOS 10.16 that left cocoapods running in the background even after all pods are installed causing even a real mac to time out. So, it wasn't just a travis thing. So, I moved to 1.9.3 and 10.15 and presto everything works and builds faster. @drdaz you where actually the one who gave me the info to find the fix lol. Unfortunately the changes you made are actually slowing the jobs down at this point. Besides just extra unnecessary tasks, you didn't override the global install or at least instruct travis to skip install to use only the job install, some things are now likely running twice. Anyway, wish I would have checked in sooner to save everyone some time. Feel free to check this out for a reference to [my changes](https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1518).

Wow. There are some false claims here that I'd like to deal with.

> You guys might have looked at what my open PR changes as it fixed a lot of this and did it in about 20 min faster and thats with doing a test cocoapod build.

I did look at your PR. I looked it through and could neither understand why those changes should fix what you claimed, nor see the results of the 'fix' in the test results. As I pointed out in the PR, your changes had no significant effect on total build time. I asked you directly in that PR to justify your changes. You ghosted.

> There is an issue with cocoapods 1.8.4 and macOS 10.16 that left cocoapods running in the background even after all pods are installed causing even a real mac to time out. So, it wasn't just a travis thing. So, I moved to 1.9.3 and 10.15 and presto everything works and builds faster.

This is demonstrably untrue. Otherwise we would have seen a change in build behaviour between [this commit](https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1525/commits/f164fe2458a49ddb30f9ede17dde261274f4abfa) and [this one](https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1525/commits/3a49208964dfcbf9104f1c831e2368f1242b24e9). This is where Xcode got bumped to 11.6 (there is, as far as I can tell, nowhere to specify a macOS version directly in our build environment configs; only Xcode version). But build times remained the same with this change. Earlier in that PR cocoapods was updated to 1.9.3. That change also didn't yield a difference in build times.

> Unfortunately the changes you made are actually slowing the jobs down at this point.

To once again make this absolutely clear, the total build time for travis on your fixes branch is ~50 mins. That's the same as it is here, and the same as it is on master. Travis sometimes runs the builds in parallel, depending on free ressources - that causes a reduction in run time for the workflow. That would explain the 20 minute difference you're seeing in *run time* on the last build triggered by your PR.

> Anyway, wish I would have checked in sooner to save everyone some time.

That sounds very thoughtful, but appears quite disingenuous. You've appeared here and proclaimed that you were right a few months ago, and that the changes we've made that don't conform to your vision are wrong and misguided.

**Comment by cbaker6** [comment]
@natekellert did you even look at the build times in your PR? They are similar to the travis ones here. Travis runs two in parallel, the way it's setup now completes 3 builds ~33 minutes. First, I'm sure you started making those changes after I initially brought up the issue, per your responses [here](https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1475#issuecomment-649338615). Second, your changes had no significant impact on the build time or to the CI in general. If you wanted to reduce the travis build time, you needed to go back to Xcode 11.3 (Mojave). This would leave the build on a particularly old CI and is probably considered outdated as Xcode 12 is about to come out.

Also, your changes really were gem lockfile updates and switching the Xcode version, you made no real changes to travis or circle, so I can't even comprehend how you making your claims. You probably should read this PR first, then come back to this one, to see how we got to this point. 

> Besides just extra unnecessary tasks, you didn't override the global install or at least instruct travis to skip install to use only the job install, some things are now likely running twice.

Incorrect, I wrote the different strategies that can be used to @drdaz on this thread, nothing is running twice (you can check the logs), the global install IS being overriden.

Lastly, the build is 50 minutes because of circle, not travis, the build is limited to the last finishing which is Circle because it runs serially, and Carthage takes ~20 minutes. If you read comments in the current PR, we discuss the reasoning for this.

**Comment by cbaker6** [comment]
@drdaz since Carthage is setup to build nightly, we can technically remove it from the PR and Push builds in circle, shrinking the total build time to ~30 minutes (travis will be the bottle neck here, but when caching is fixed, this should shrink ~20 minutes). 

Is it's an change if you think it makes sense

**Comment by drdaz** [comment]
@cbaker6 Personally I like that it's here (on PRs) too; I think it gives master a better chance of staying usable. And less chance of having to panic-fix the day after a merge 😃

**Comment by cbaker6** [comment]
np... It looks like codecov is now showing up through GitHub Actions instead of going straight to its site. I believe this is why it's not showing the percentage here, but you can see it by clicking on "Details"; it's back to normal. I'm guessing GitHub made an update to how codecov is integrated.

**Comment by cbaker6** [comment]
The cache is fixed, the bundle install for travis went from > 5 minutes to < 1 sec. So travis should finish at ~25 minutes from now on

**Review by cbaker6 — APPROVED** [review]

**Review by cbaker6 — APPROVED** [review]

**Comment by drdaz** [comment]
Nice!

Have you got any idea how this is possible btw? According to the travis report, travis run time was shorter than the deployment build's.

Screenshot 2020-09-05 at 21 15 57

**Comment by cbaker6** [comment]
> Have you got any idea how this is possible btw? According to the travis report, travis run time was shorter than the deployment build's.

I'm sure that's a bug in travis on their web side. It seems to use the last running build for that time. But I watched the builds finish a couple of times, travis finishes a couple minutes after circle with the latest changes, with both of them completing < 40 minutes.

The order the builds start on travis are:

1. Deployment: (Concurrent 1)
2. Facebook_Utils: (Concurrent 2)
3. Twitter_Utils: (Concurrent 2) 
4. ParseUI: (Concurrent 2)
5. Cocoapods: (Concurrent 2)
6. Docs: (Concurrent 1)

The order the builds complete on travis are:

1. Facebook_Utils: (Concurrent 2)
2. Twitter_Utils: (Concurrent 2)
3. ParseUI: (Concurrent 2)
4. Deployment: (Concurrent 1)
5. Docs: (Concurrent 1)
6. Cocoapods: (Concurrent 2)

**Comment by drdaz** [comment]
2 of the travis tasks failed after I pushed the 1.19.0 tag - deployment and cocoapods.

Deployment failed with this:

> Installing deploy dependencies
> 11729/Users/travis/.rvm/gems/ruby-2.6.6/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://docs.github.com/rest (Octokit::Unauthorized)

And in the Cocoapods build these outputs caught my attention:

> Parse passed validation.
> 842/Users/travis/.travis/functions: line 607:  3936 Terminated: 15          travis_jigger "${!}" "${timeout}" "${cmd[@]}"

and

> Deploying application
> 863Script failed with status 127

**Comment by cbaker6** [comment]
It looks like both have to do with incorrect credentials. TBH, I don't know what the "Deployment" release is for. If it is something that isn't needed anymore, it would save a significant amount of time in the build. I left it, because I didn't know how important it is.

> Parse passed validation.
842/Users/travis/.travis/functions: line 607: 3936 Terminated: 15 travis_jigger "${!}" "${timeout}" "${cmd[@]}"

I believe this comes from `travis_wait`, I don't think it cause the issue. I'm guessing the trunk key from cocoa pods may be invalid. I remember @TomWFox mentioned somewhere that these expire when not used after awhile.

Since the deployments on tags haven't been tested (at least by me), I can see why we didn't run into these issues until now

**Comment by cbaker6** [comment]
A good thing, it looks like the docs are back to deploying!

**Comment by drdaz** [comment]
> A good thing, it looks like the docs are back to deploying on tags!

Sweet!

> I don't know what the "Deployment" release is for in travis

Looking at what it runs (package:release) I assume it's creating release assets, if not for distribution (I'm actually not sure where our downloadables are created), then to test that it's actually possible to generate them from our codebase.

> 842/Users/travis/.travis/functions: line 607: 3936 Terminated: 15 travis_jigger "${!}" "${timeout}" "${cmd[@]}"
> I believe this comes from travis_wait, I don't think it caused the issue

Confirmed that it didn't cause this; it appears in the passed builds in this PR too.

> Cocoapods deployment timed out after 10 minutes

The drill down in the 'Deploying application' phase shows a return code of 127, which usually means a command is missing. I find it odd that the build didn't fail right there.

Merging this PR triggered a build on master that passed (wouldn't that use the trunk key?). What's different here? If I'm reading the travis yml right, the deployment and cocoapods tasks should be run just the same on a tag as on a branch?

**Comment by cbaker6** [comment]
> Merging this PR triggered a build on master that passed (wouldn't that use the trunk key? EDIT: I guess if it's cocoapods trunk we're talking about, it wouldn't). What's different here? If I'm reading the travis yml right, the deployment and cocoapods tasks should be run just the same on a tag as on a branch?

The deployments in travis only run on the tags, see the previous Cocoapods log [here](https://travis-ci.org/github/parse-community/Parse-SDK-iOS-OSX/jobs/722490312). There it shows "Skipping deployment" which makes sense as cocoa pods would fail if we pushed on every commit on master because we are not bumping the version in the pod spec.

The way I interpret the travis deployment in this yml is deploy on tags on any branch.

**Comment by drdaz** [comment]
Yeah that makes sense that it leaves cocoapods deploy alone unless we tag. Also makes sense looking at the yml.

**Comment by drdaz** [comment]
The 'Deployment' job though... that doesn't look like it does anything pods-related.

**Comment by cbaker6** [comment]
> The 'Deployment' job though... that doesn't look like it does anything pods-related.

Yes, I wasn't trying to imply that it does, it looks like it builds the release projects and adds the zip files to a folder for people to download(I'm guessing on the download part)? That has it's own key in travis that @TomWFox might now about. My guess is that key is either expired or needs to be setup again. Depending on the importance of "Deployment", I was recommending to remove it if possible

**Comment by drdaz** [comment]
> Yes, I wasn't trying to imply that it does

I know; that was a faulty assumption on my part 🙂

**Comment by cbaker6** [comment]
One thing I do see in the [documentation](https://docs.travis-ci.com/user/deployment/#examples-of-conditional-deployment) for deployments in travis is that it can use `api_key`, ours is currently using `token`:

```
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
    rvm: 2.0.0
```

**Comment by drdaz** [comment]
> Update*: Looking further, it looks like this create the zip files for each package described at the beginning of the readme. I've always used pods for this framework, so this never occurred to me. Do people actually use this? 

There's at least one chap using it; there's an open issue about the assets for tvOS not being present for the 1.18 release. None of the others are either.

> Thinking a little more, I can understand the importance of "Deployment" and why its deployed here because if the rake doesn't create the zips, they probably won't build properly when using them directly from github

Precisely. It's a very good thing to test generating release assets.

**Comment by TomWFox** [comment]
Hi guys, sorry I haven't been involved here - been on holiday! As no one seems to know sure what caused this issue I'm wondering whether we go for a manual release again... then perhaps we could clone the repo and setup a dummy pod to test the release mechanism?

**Comment by drdaz** [comment]
> Hi guys, sorry I haven't been involved here - been on holiday! As no one seems to know how to resolve this issue I'm wondering whether we go for a manual release again... then perhaps we could clone the repo and setup a dummy pod to test the release mechanism?

Hey no worries. Yeah I think we should get the release available asap, and we should definitely find some way of validating the release mechanics.

Did you do the manual release last time? If so, do you feel like doing it again? 😃

I just checked the man for git push. There's an option for a dry run (-n), which the man describes as: 

> Do everything except actually send the updates.

Maybe we could use this switch generally, but drop it when triggered by a tag. If I've understood that description correctly, it should show up any auth issues. And maybe keep the credentials alive if they expire due to disuse.

**Comment by drdaz** [comment]
But yes to the dummy pod idea... that could definitely work. And we can clean things up with trunk delete when the testing is done.

**Comment by natekellert** [comment]
@drdaz I was comparing run times not total time and no they are not the same thing.

I just realized this is under my work github and not @noobs2ninjas on this computer. I have spent a vast amount of my time between 1.17.3 and 1.18.0 working on the builds. When I came along the builds where so bad that we couldn't push a build out even if we wanted to. It had been 8 months since the last release and no one was actually working on parse at all at that point. 

Lastly, it was very true that the current version of Xcode, the OS version, the version of cocoapods had issues. I even sent you the link at the time. Maybe thats not the case now, but it certainly was back then. Talk crap all you want but when I was trying to fix it back the thing you worked on the most was criticism.

**Comment by drdaz** [comment]
> @drdaz and @cbaker6 I was talking cocoapod run times directly in reference to the changes you made. Now that the status panels are gone I dont really have anything to say you aren't correct. I probably was wrong.

The build records aren't gone. Here are the travis results from this PR: 
https://travis-ci.org/github/parse-community/Parse-SDK-iOS-OSX/builds/724452751

Hopefully this puts the matter of what works and what doesn't to rest.

> I have spent a vast amount of my time between 1.17.3 and 1.18.0 working on the builds. When I came along the builds where so bad that we couldn't push a new release out even if we wanted to. It had been 8 months since the last release and no one was actually working on parse at all at that point.

And nobody is denying that, nor trying to take that away from you.

> So I don't think anyone has the ability to tell me what I am or am not genuine about.

I told you how your approach in this thread appeared to me. I'd be lying to you if I acted like it didn't press some buttons.

> Lastly, to @drdaz it was very true that the current version of Xcode, the OS version, the version of cocoapods had issues. I even sent you the link at the time with the cocoapods open ticket.

Alright. I don't remember that. But whatever the issue was, I didn't see it in our builds, and you didn't explain it in the PR.

**Comment by TomWFox** [comment]
@drdaz I think you did the last two releases manually. I’m happy to give it a shot but won’t be able to until late Thursday/Friday.

**Comment by drdaz** [comment]
@TomWFox I definitely didn't do the last one... but now you mention it 1.17.3 I might well have pushed to cocoapods. 

[Time passes]

Well since it turns out I can do that, I did:

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  Parse (1.19.0) successfully published
 📅  September 8th, 21:18
 🌎  https://cocoapods.org/pods/Parse
 👍  Tell your friends!
--------------------------------------------------------------------------------

**Comment by TomWFox** [comment]
Awesome, thanks!

**Comment by natekellert** [comment]
@drdaz 

Looking at the builds. I have no Idea where I was getting that number. Maybe I was looking at CircleCI? Are you doing a Cocoapod test build there? Anyway, sorry if I was wrong. 

>  I told you how your approach in this thread appeared to me. I'd be lying to you if I acted like it didn't press some buttons.

I didn't think about it from that perspective. Guess I was just irritated in general that I've not been able to contribute due to new job and child. So, I can see how my tone came off a little like "I'll tell you where you're all wrong." after not having been around for a bit. Guess I was a bit jealous that everything was moving forward without me. 

Don't know if you remember but during the Apple Sign In addition you where experiencing build time-outs. I think it was the first travis XCode environment that used 16.0 was giving us fits. Prior to that it was working but that little extra build time on that PR was pushing it past its limit. Thats why I ended up working on the other PR. I was fixing the build to the Apple Sign In PR to get it to work before merging but everyone wanted me to put it on a separate branch and PR.

**Pull request merged**
