### PR TITLE
Release 1.17.2

### PR DESCRIPTION
**Pull request by kennic**
- Renamed PFFile to PFFileObject
- Fixed crash when saving PFPolygon to object
- Bumps version to 1.17.2
- Bumps cocoapods

### CODE REVIEW

**Comment by kennic** [comment]
@flovilmart  can you please merge this, then add 1.17.2 release tag and deploy it on cocoapods? I've update the version but I don't have rights to add tag and deploy it.

**Comment by flovilmart** [comment]
Working on it :)

**Comment by flovilmart** [comment]
The tag and pre-built pacakges are all available, there seems to be some issues with cocoapods, xcode 10 et. al. It's taking a bit longer for publishing the pods.

**Comment by flovilmart** [comment]
It should be published now.

**Comment by kennic** [comment]
> It should be published now.

awesome, thank you!

**Comment by natanrolnik** [comment]
I've updated the docs in Obj-C that were missing here: https://github.com/parse-community/docs/pull/580/files
Also, yesterday we merged this one: https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1382

**Pull request merged**
