### PR TITLE
Improve CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by TomWFox**
#1422

### CODE REVIEW

**Comment by TomWFox** [comment]
@drdaz Good point 😂, I'll test it.

**Comment by TomWFox** [comment]
@drdaz can confirm this works

**Comment by TomWFox** [comment]
@brianyyz how does this look to you?

**Comment by brianyyz** [comment]
Looks good @TomWFox - I'll try to keep notes of things I run up against trying to get more involved.

**Pull request merged**
